development:
  adapter: mysql2
  encoding: utf8
  database: upload_server_development
  username: root
  password: root 
  pool: 5
  timeout: 5000
  reconnect: true

test:
  adapter: mysql2
  encoding: utf8
  database: upload_server_development
  username: root
  password: root
  pool: 5
  timeout: 5000
  
production:
  adapter: mysql2
  encoding: utf8
  database: upload_server
  username: root
  password: root
  pool: 5
  timeout: 5000
  reconnect: true
